wvchallenges/se-challenge-payroll/solution/config/routes.rb
Rails.application.routes.draw do
  get 'report/index', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report/json(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#show_json', default: { pay_period: 'semimonthly' }

  get 'timesheet/index'
  get 'timesheet/upload'
  post 'timesheet/create'
  get 'timesheet' => 'timesheet#index'

  resources :employees, :workgroups, :dailyworks, :timesheet_status

  root to: 'report#index', default: { pay_period: 'semimonthly' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

wvchallenges/se-challenge-payroll/solution/app/models/workgroup.rb
class Workgroup < ApplicationRecord
  validates :category, presence: true
  validates :rate, numericality: { greater_than: 0 }

  # class << self; attr_accessor :category_map end
  # @category_map = build_category_map()

  def self.build_category_map
    @cate_map = Hash.new
    Workgroup.all.map { |g| @cate_map[g.category] = g.id }
    return @cate_map
  end
  
end

wvchallenges/se-challenge-payroll/solution/app/controllers/workgroups_controller.rb
class WorkgroupsController < ApplicationController
  def index
    @workgroups = Workgroup.all
  end
  
  def new
    @workgroup = Workgroup.new
  end
  
  def create
    @workgroup = Workgroup.new(workgroup_params)
    
    @workgroup.save!

    redirect_to :action => :index
  end
  

  private

  def workgroup_params
    params.require(:workgroup).permit(:category, :name, :rate)
  end
end

wvchallenges/se-challenge-payroll/solution/app/helpers/workgroups_helper.rb
module WorkgroupsHelper
end

wvchallenges/se-challenge-payroll/solution/app/views/workgroups/index.html.erb
<h1>Work Groups</h1>

<div class="Table">
  <div class="Table-row Table-header">
    <div class="Table-row-id-item">Group ID</div>
    <div class="Table-row-item">Category</div>
    <div class="Table-row-item">Name</div>
    <div class="Table-row-item">Rate</div>
  </div>
<% @workgroups.each do |group| %>
  <div class="Table-row">
    <div class="Table-row-id-item" data-header="Group ID"><%= group.id %></div>
    <div class="Table-row-item" data-header="Category"><%= group.category %></div>
    <div class="Table-row-item" data-header="Name"><%= group.name %></div>
    <div class="Table-row-item" data-header="Rate"><%= group.rate %></div>
  </div>
<% end %>
</div>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'New work group', :controller => 'workgroups', :action => 'new' %>
</div>

wvchallenges/se-challenge-payroll/solution/app/views/workgroups/new.html.erb
<h1>New work group</h1>

<%= form_for @workgroup, url: workgroups_path do |f| %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'Back to report', :controller => 'report', :action => 'index', :default => { pay_period: 'semimonthly' } %>
</div>