wvchallenges/se-challenge-payroll/solution/config/routes.rb
Rails.application.routes.draw do
  get 'report/index', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report/json(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#show_json', default: { pay_period: 'semimonthly' }

  get 'timesheet/index'
  get 'timesheet/upload'
  post 'timesheet/create'
  get 'timesheet' => 'timesheet#index'

  resources :employees, :workgroups, :dailyworks, :timesheet_status

  root to: 'report#index', default: { pay_period: 'semimonthly' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

wvchallenges/se-challenge-payroll/solution/app/models/dailywork.rb
class Dailywork < ApplicationRecord
  belongs_to :employee
  belongs_to :workgroup
  validates :date, presence: true
  validates :hours, numericality: { greater_than: 0 }
  validates :report_id, numericality: { greater_than: 0 }

  default_scope { order(employee_id: :asc) }

  scope :bewteen_start_end_date, ->(start_date, end_date) { where("date BETWEEN datetime('#{start_date}') AND datetime('#{end_date}')") }
  scope :from_start_date, ->(date) { where("date >= datetime('#{date}')") }
  scope :to_end_date, ->(date) { where("date <= datetime('#{date}')") }
  scope :employee, ->(employee_id) { where("employee_id = #{employee_id}") }
  scope :workgroup, ->(group_id) { where("workgroup_id = #{group_id}") }
  
  def self.find_rows_sorted_by_employee_id(startDatetime, endDatetime, workgroupId, employeeId)
    if startDatetime.present? && endDatetime.present?
      @found = Dailywork.send(:bewteen_start_end_date, startDatetime, endDatetime)
      
      if workgroupId.present?
        @found = @found.send(:workgroup, workgroupId)
      end
      
      if employeeId.present?
        @found = @found.send(:employee, employeeId)
      end

      return @found
    end
    
    if startDatetime.present?
      @found = Dailywork.send(:from_start_date, startDatetime)

      if workgroupId.present?
        @found = @found.send(:workgroup, workgroupId)
      end
      
      if employeeId.present?
        @found = @found.send(:employee, employeeId)
      end

      return @found
    end
    
    if endDatetime.present?
      @found = Dailywork.send(:to_end_date, endDatetime)

      if workgroupId.present?
        @found = @found.send(:workgroup, workgroupId)
      end
      
      if employeeId.present?
        @found = @found.send(:employee, employeeId)
      end

      return @found
    end

    if workgroupId.present?
      @found = Dailywork.send(:workgroup, workgroupId)

      if employeeId.present?
        @found = @found.send(:employee, employeeId)
      end

      return @found
    end

    if employeeId.present?
      @found = Dailywork.send(:employee, employeeId)

      return @found
    end

    @found = Dailywork.all
    return @found
  end

end

wvchallenges/se-challenge-payroll/solution/app/controllers/dailyworks_controller.rb
class DailyworksController < ApplicationController
  def index
    @dailyworks = Dailywork.reorder(nil).all
  end
  
  def new
    @dailywork = Dailywork.new
  end
  
  def create
    @dailywork = Dailywork.new(dailywork_params)
    
    @dailywork.save!

    redirect_to :action => :index
  end
  

  private

  def dailywork_params
    params.require(:dailywork).permit(:employee_id, :workgroup_id, :date, :hours, :report_id)
  end
end

wvchallenges/se-challenge-payroll/solution/app/helpers/dailyworks_helper.rb
module DailyworksHelper
end

wvchallenges/se-challenge-payroll/solution/app/views/dailyworks/index.html.erb
<h1>Daily Works</h1>

<div class="Table">
  <div class="Table-row Table-header">
    <div class="Table-row-id-item">Work ID</div>
    <div class="Table-row-item">Employee ID</div>
    <div class="Table-row-item">Date</div>
    <div class="Table-row-item">Hours</div>
    <div class="Table-row-item">Group ID</div>
    <div class="Table-row-item">Report ID</div>
  </div>
<% @dailyworks.each do |work| %>
  <div class="Table-row">
    <div class="Table-row-id-item" data-header="Work ID"><%= work.id %></div>
    <div class="Table-row-item" data-header="Employee ID"><%= work.employee_id %></div>
    <div class="Table-row-item" data-header="Date"><%= work.date %></div>
    <div class="Table-row-item" data-header="Hours"><%= work.hours %></div>
    <div class="Table-row-item" data-header="Group ID"><%= work.workgroup_id %></div>
    <div class="Table-row-item" data-header="Report ID"><%= work.report_id %></div>
  </div>
<% end %>
</div>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'New daily work', :controller => 'dailyworks', :action => 'new' %>
</div>

wvchallenges/se-challenge-payroll/solution/app/views/dailyworks/new.html.erb
<h1>New dailywork</h1>

<%= form_for @dailywork, url: dailyworks_path do |f| %>
  <p>
    <%= f.label :employee_id, "Employee ID" %><br>
    <%= f.text_field :employee_id %>
  </p>
 
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </p>

  <p>
    <%= f.label :workgroup_id, "Group ID" %><br>
    <%= f.text_field :workgroup_id %>
  </p>

  <p>
    <%= f.label :report_id, "Report ID" %><br>
    <%= f.text_field :report_id %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'Back to report', :controller => 'report', :action => 'index', :default => { pay_period: 'semimonthly' } %>
</div>