wvchallenges/se-challenge-payroll/solution/config/routes.rb
Rails.application.routes.draw do
  get 'report/index', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#index', default: { pay_period: 'semimonthly' }
  get 'report/json(/start/:start_datetime)(/end/:end_datetime)(/group/:workgroup_id)(/employee/:employee_id)(/period/:pay_period)', to: 'report#show_json', default: { pay_period: 'semimonthly' }

  get 'timesheet/index'
  get 'timesheet/upload'
  post 'timesheet/create'
  get 'timesheet' => 'timesheet#index'

  resources :employees, :workgroups, :dailyworks, :timesheet_status

  root to: 'report#index', default: { pay_period: 'semimonthly' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

wvchallenges/se-challenge-payroll/solution/app/models/employee.rb
class Employee < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  enum gender: [ :unknown, :male, :female ]

  def self.build_id_list
    @ids = Array.new
    Employee.all.map { |e| @ids << e.id }
    return @ids
  end
  
end

wvchallenges/se-challenge-payroll/solution/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end
  
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    
    @employee.save!

    redirect_to :action => :index
  end


  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :gender, :description)
  end
end

wvchallenges/se-challenge-payroll/solution/app/helpers/employees_helper.rb
module EmployeesHelper
end

wvchallenges/se-challenge-payroll/solution/app/views/employees/index.html.erb
<h1>Employees</h1>

<div class="Table">
  <div class="Table-row Table-header">
    <div class="Table-row-id-item">Employee ID</div>
    <div class="Table-row-item">Name</div>
    <div class="Table-row-item">Gender</div>
    <div class="Table-row-item">Description</div>
  </div>
<% @employees.each do |employee| %>
  <div class="Table-row">
    <div class="Table-row-id-item" data-header="Employee ID"><%= employee.id %></div>
    <div class="Table-row-item" data-header="Name"><%= "#{employee.first_name} #{employee.last_name}" %></div>
    <div class="Table-row-item" data-header="Gender"><%= employee.gender %></div>
    <div class="Table-row-item" data-header="Description"><%= employee.description %></div>
  </div>
<% end %>
</div>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'New employee', :controller => 'employees', :action => 'new' %>
</div>

wvchallenges/se-challenge-payroll/solution/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= form_for @employee, url: employees_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :gender %><br>

    <%= f.radio_button :gender, 'unknown', :checked => true %> 
    <%= label :gender_unknown, 'Unknown' %>
    <%= f.radio_button :gender, 'male' %>
    <%= label :gender_male, 'Male' %>
    <%= f.radio_button :gender, 'female' %>
    <%= label :gender_female, 'Female' %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<div class="w3-btn w3-white w3-border w3-border-blue w3-round">
  <%= link_to 'Back to report', :controller => 'report', :action => 'index', :default => { pay_period: 'semimonthly' } %>
</div>